[project]
name = "python-anything"
version = "0.1.0"
description = "Python project starter with a modern setup"
license = "MIT"
authors = [
    { name = "Ülgen Sarıkavak", email = "foss@ulgenwanders.net" },
]
requires-python = "==3.14.*"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "copier-template-extensions==0.3.3",
    "httpx==0.28.1",
    "jinja2==3.1.6",
]

[dependency-groups]
dev = [
    "copier==9.17.0",
    "ipdb==0.13.13",
    "ipython==9.15.0",
    { include-group = "test" },
]
test = [
    "faker==40.36.0",
    "pytest==9.1.1",
    "pytest-randomly==4.1.0",
    "pytest-xdist==3.8.0",
]

[tool.uv]
# The earliest version that supports the current lock file revision
required-version = ">=0.8.4"
package = false
