indent = 4
keep_full_version = true
table_format = "long"
sub_table_spacing = "\n"
# Keeping it closer to
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#authors-maintainers
collapse_tables = [
    "project.authors",
    "project.maintainers",
]
