name: "Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: ~

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=python-version depName=python
  PYTHON_VERSION: 3.14.6
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.11.26

jobs:
  run-tests:
    name: pytest
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv ${{ env.UV_VERSION }} & Python ${{ env.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}

      - name: Install the dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest
