name: "Test application generation"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: ~

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # TODO: How to define a matrix without losing renovate support for the versions?
  # renovate: datasource=python-version depName=python
  PYTHON_VERSION: 3.14.6
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.11.24
  OUTPUT_PATH: /tmp/test-application

jobs:
  run-tests:
    name: pytest
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv ${{ env.UV_VERSION }}
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}

      - name: Install the dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest tests/test_application.py
